# -*- coding: utf-8 -*-
"""project1inpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/VINU-J/db11659aabf01aab3c6333bb56528554/project1inpy.ipynb

RANDOM PASSWORD GENERATOR
"""

import random
print("THANKS FOR CHOOSING OUR SERVICE")
print("WELCOME TO RANDOM PASSWORD GENERATOR!")
randomchars = "123456789!@#$%^&*qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM"
numberofpasswords = int(input("pls enter the number of passwords to be generator:"))
passwordlength = int(input("please enter the length of the password needed:"))
print("Hear are your random password:")
for x in range(numberofpasswords):
  password=""
  for chars in range(passwordlength):
    password = password + random.choice(randomchars)
  print(password)